language: node_js
sudo: required
node_js:
    - "node"
script:
    - echo "test"
    - ./generate.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
